name: conekta_flutter
description: Flutter plugin that allows you to create credit card tokens using the Conekta payment gateway.
version: 0.0.4-nullsafety
homepage: https://github.com/apeiro-tech/conekta_flutter.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.apeirotechnologies.conekta_flutter
        pluginClass: ConektaFlutterPlugin
      ios:
        pluginClass: ConektaFlutterPlugin